name: PlayGround Debug

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3

    - name: Touch Local.Properties
      run: touch Local.Properties

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Pre build
      run: ./gradlew app:preBuild

    - name: Detekt
      run: ./gradlew app:detekt

    - name: Build with Gradle
      run: ./gradlew app:assembleDebug

    - name: Run unit test
      run: ./gradlew test